baseURL = "https://stagbar.github.io/"
defaultContentLanguage = "zh-hans"
title = 'My New Hugo Project'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
custom_css = ["custom.css"]